name: 里奥梅西介绍页  Leo messi Introduction
url: https://Leo-10-neymar.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8
# Sections on the "people" page.
roles:
  - key: faculty
    name: 本人 He
  - key: grad
    name: 妻子 Wife
  - key: collab
    name: 好友 Friend


# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: 主页 Home
    link: /
  - title: 俱乐部 Club
    link: /research.html
  - title: 荣誉 Honor
    link: /publications.html
